select * from customer limit 20;

--1. What is the total revenue generated by male vs. female customers?
select gender,SUM(purchase_amount) as revenue
from customer
group by gender

select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

select shipping_type,
ROUND(AVG(purchase_amount), 2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;

SELECT SUBSCRIPTION_STATUS,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

WITH customer_type AS(
SELECT customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)
SELECT customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;


WITH item_counts as (
select category, item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category order by count(customer_id) DESC) AS item_rank
from customer
group by category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

select  subscription_status, 
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;



